### ISSUE TITLE
I'm having some weird troubles with arch-update blocklet

### ISSUE THREAD

**Issue by Pxmme** [vivien/i3blocks-contrib#96] opened 2017-06-15 12:26 UTC
### Expected behavior

Check every 10 minutes if new update available. If so, show a red " 1" on my bar (using awesome fonts which is of course installed on my arch)

If no new update is available, simply display a white " 0" on my bar.

### Actual behavior

I have two issues which are very weird to me with this.

First one : I can't get any display on my bar when there is no update available. I would like to have a white " 0" on my bar, so I know that the script is running, that it checked for me and that there is in fact no new updates for me to do... I did everything in the script for that to happen, but still : nothing.

Second one : it seems to not run the script automatically every ten minutes as it's supposed to, because sometimes, I manually check for updates available (pacman -Syyu), and there is, but nothing is up on my bar... Then I press $mod + shift + R to reload i3, and then it shows  1 on my bar!!!

### i3blocks config relevant to blocklet(s)

/usr/lib/i3blocks/arch-update.py : 

```
#!/usr/bin/env python3
#
# Copyright (C) 2017 Marcel Patzwahl
# Licensed under the terms of the GNU GPL v3 only.
#
# i3blocks blocklet script to see the available updates of pacman and the AUR
from subprocess import check_output
import argparse


def create_argparse():
    parser = argparse.ArgumentParser(description='Check for pacman updates')
    parser.add_argument(
        '-b',
        '--base_color',
        default='white',
        help='base color of the output(default=green)'
    )
    parser.add_argument(
        '-u',
        '--updates_available_color',
        default='red',
        help='color of the output, when updates are available(default=yellow)'
    )
    parser.add_argument(
        '-a',
        '--aur',
        action='store_true',
        help='Include AUR packages. Attn: Yaourt must be installed'
    )
    return parser.parse_args()


def get_update_count():
    output = check_output(['checkupdates']).decode('utf-8')
    if not output:
        return 0

    updates = [line
               for line in output.split('\n')
               if line]

    return len(updates)


def get_aur_update_count():
    output = check_output(['yaourt', '-Qua']).decode('utf-8')
    if not output:
        return 0

    aur_updates = [line
                   for line in output.split('\n')
                   if line.startswith('aur/')]

    return len(aur_updates)


message = "<span color='{0}'>{1}</span>"
args = create_argparse()

update_count = get_update_count()

if args.aur:
    update_count += get_aur_update_count()
if update_count == 0:
    info = ' ' + str(update_count)
    print(message.format(args.base_color, info))
else:
    info = ' ' + str(update_count)
    print(message.format(args.updates_available_color, info))

```
~/.config/i3/i3blocks.conf : 
```
# i3blocks config file
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks
#
# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.
command=/usr/lib/i3blocks/$BLOCK_NAME
separator_block_width=15
markup=none

# Memory usage
#
# The type defaults to "mem" if the instance is not specified.
[memory]
label=
separator=false
interval=30

# CPU usage
#
# The script may be called with -w and -c switches to specify thresholds,
# see the script for details.
[cpu_usage]
label=
interval=2
min_width=CPU:
separator=false


#[memory]
#label=SWAP
#instance=swap
#separator=false
#interval=30

# Disk usage
#
# The directory defaults to $HOME if the instance is not specified.
# The script may be called with a optional argument to set the alert
# (defaults to 10 for 10%).
[disk]
label=
#instance=/mnt/data
interval=30

[wifi]
instance=wlp3s0
interval=10
separator=false

# Network interface monitoring
#
# If the instance is not specified, use the interface used for default route.
# The address can be forced to IPv4 or IPv6 with -4 or -6 switches.
#[iface]
#instance=wlan0
#color=#00FF00
#interval=10
#separator=true

#[bandwidth]
#instance=eth0
#interval=5

#[load_average]
#interval=10

# Battery indicator
#
# The battery instance defaults to 0.
[battery]
#instance=1
interval=60

# Volume indicator
#
# The first parameter sets the step (and units to display)
# The second parameter overrides the mixer selection
# See the script for details.
[volume]
label=♪
instance=Master
#instance=PCM
interval=1
signal=10

[arch-update]
command=/usr/lib/i3blocks/arch-update.py -a -b "#FFFFFF" -u "#FF0000"
markup=pango
interval=600
separator=true

[email]
command=/usr/lib/i3blocks/email
label=
interval=120
separator=true

# Date Time
#
[time]
command=date '+%Hh%M '
interval=1

# Generic media player support
#
# This displays "ARTIST - SONG" if a music is playing.
# Supported players are: spotify, vlc, audacious, xmms2, mplayer, and others.
#[mediaplayer]
#interval=1
#instance=vlc

# OpenVPN support
#
# Support multiple VPN, with colors.
#[openvpn]
#interval=20

# Temperature
#
# Support multiple chips, though lm-sensors.
# The script may be called with -w and -c switches to specify thresholds,
# see the script for details.
#[temperature]
#label=TEMP
#interval=10

# Key indicators
#
# Add the following bindings to i3 config file:
#
# bindsym --release Caps_Lock exec pkill -SIGRTMIN+11 i3blocks
# bindsym --release Num_Lock  exec pkill -SIGRTMIN+11 i3blocks
#[keyindicator]
#instance=CAPS
#interval=once
#signal=11

#[keyindicator]
#instance=NUM
#interval=once
#signal=11
```

### Output of blocklet(s) when run from command line

WHEN NO UPDATE AVAILABLE : 
```
$ python /usr/lib/i3blocks/arch-update.py 
<span color='white'> 0</span>
```

WHEN UPDATE AVAILABLE
```
python /usr/lib/i3blocks/arch-update.py 
<span color='red'> 2</span>
```

### Output of any relevant other commands that might help diagnostics

Here is a screenshot of what it shows me when I have updates available, and when I did press $mod + shift + R : 

![2017-06-15-jun-1497479640_1366x768](https://user-images.githubusercontent.com/22918318/27181047-248d05ce-51d6-11e7-8b5c-b7e8ad6891fb.png)

(please don't pay attention to the display order being 8 instead of  8, I changed it between the time I took this scrot and now :) )

**Comment by Pxmme** [comment] 2017-06-15 12:30
I am sorry for the appearance of my message, I don't know why I can't just deactivate this "text formatting" b***s*** :(

And I'd also like to apologize for any English mistakes I may have done, English is not my mothertongue. As you might see on my screenshot, I'm French.

Thanks in advance for any help you might give me! :)

**Comment by snowiow** [comment] 2017-06-15 13:22
Hi can you please edit your message, so that your code is inside code markup? Have a look [here](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code) if you don't know how to do it. Thanks

**Comment by Pxmme** [comment] 2017-06-15 13:28
Hi snowiow,

I'll get on that right now, thanks for answering :) :+1:

**Comment by snowiow** [comment] 2017-06-15 13:33
thanks :) I will have a look into it

**Comment by Pxmme** [comment] 2017-06-15 14:01
Hey I've got some news : 

When I take the -a out of the command in i3blocks.conf, everything works.

Odd thing is : yaourt in installed and running on my arch system. I often use it, I have aur packages... so WTH ?

**Comment by snowiow** [comment] 2017-06-15 14:03
Yes the problem is that yaourt exits with a non zero status when it has no updates. Python subprocess thinks there was an error during the execution und raises it

**Comment by snowiow** [comment] 2017-06-15 14:04
```
def get_aur_update_count():
    output = ''
    try:
        output = check_output(['yaourt', '-Qua']).decode('utf-8')
    except subprocess.CalledProcessError as e:
        print("Ping stdout output:\n", e.output)
    if not output:
        return 0

    aur_updates = [line
                   for line in output.split('\n')
                   if line.startswith('aur/')]

    return len(aur_updates)
```
you can check yourself, if you update the method like this

**Comment by Pxmme** [comment] 2017-06-15 14:05
I just tried "yaourt -Qua" and it seems to be working just find, no output at all because no update is available. This situation is expected in the py script : 
```
    if not output:
        return 0
```
So I'm wondering : why is this not working?

**Comment by Pxmme** [comment] 2017-06-15 14:12
Alright so I tried and edited my py script, added your modification, then restarted i3.

Nothing appears on top no more. I have one update available, so the script's sending back to me <span color='yellow'> 1</span>, but nothing on the bar. :(

This is just odd.

**Comment by Pxmme** [comment] 2017-06-15 14:15
After a few tests, I can confirm that, at least, without the -a option, **everything works just fine**, so the issue is definitly about yaourt and AUR updates.

**Comment by snowiow** [comment] 2017-06-15 14:17
if you change the python script in the yaourt -Qua line as follows: 
`output = check_output(['yaourt', '-Su', '--aur']).decode('utf-8')`
do you get an update messge in your bar?

**Comment by Pxmme** [comment] 2017-06-15 14:23
So this is how my codes look like right now : 

```
def get_aur_update_count():
    output = ''
    try:
        output = check_output(['yaourt', '-Su', '--aur']).decode('utf-8')
    except subprocess.CalledProcessError as e:
        print("Ping stdout output:\n", e.output)
    if not output:
        return 0

    aur_updates = [line
                   for line in output.split('\n')
                   if line.startswith('aur/')]

    return len(aur_updates)
```

```
[arch-update]
command=/usr/lib/i3blocks/arch-update.py -a -b "#FFFFFF" -u "#FF0000"
interval=600
markup=pango
```

And... it seems to work fine! I mean, I do not have any update available for now, but I do have the update status in my bar, right how and where it should be!

Thanks a lot for your help, man. May I ask, because I am no python expert, what was wrong with the script in the first place?

**Comment by snowiow** [comment] 2017-06-15 14:29
It wasn't really a problem with the script itself. The problem was that -Qua returned a non 0 status code. The python subprocess module interpretes that as an error and so the script was aborted. Normally yaourt -Qua should also exit with a 0 status code when it has no updates like -Su does. So there are two ways. To keep the -Su argument or catch the exception and check if the catched error is infact empty and go on, because it wasn't a real error

**Comment by Pxmme** [comment] 2017-06-15 14:33
Well, sir, you obviously are much better in Python than I am. I'm still learning tho.

Thanks for the explanation, thanks for answering me, and resolving my issue.

I'm wondering... The modification you made... Shouldn't it be put in the default script, so that other users can benefit from it?

Sorry if I'm saying nonsense, I'm quite new to github too.

**Comment by snowiow** [comment] 2017-06-15 14:37
No you are right :smile: . But I'm still fiddling around, what will be the best solution to that problem. I will give you an update here, if the code is updated in the repository

**Comment by kb100** [comment] 2017-06-15 14:38
@snowiow  Thanks for handling this one. If you think this may be a common issue, I would merge the fix for it, and @Pxmme if your issue is resolved please close the issue.

**Comment by Pxmme** [comment] 2017-06-15 14:38
Hey, anyway, thanks again man. I really appreciate how quick you helped me.

I guess I have to put this issue in "resolved" mode now... Let's see how to do that. :)

**Comment by Pxmme** [comment] 2017-06-15 14:39
Yay! Done, @kb100 👍

**Closed** 2017-06-15 14:39 UTC

**Comment by snowiow** [comment] 2017-06-15 15:21
problem will be fixed with #97

**Comment by Pxmme** [comment] 2017-06-15 18:39
@snowiow I updated my arch-update.py with the #97 modifications you made, since they were a little bit different from the solution you offered me here :+1: 

**Everything seems to work just fine!**

Merci encore :)

**Comment by snowiow** [comment] 2017-06-15 20:26
Yes I liked that solution more than the first one. Glad it's working now. Thanks for your help
